name: GoCD
markdown: redcarpet
pygments: false
future: false
navigation:
- root: Blog
  url: /blog.html
  icon: icon-comment
- root: Learn more
  url: #
  icon: icon-help-circled-1 
  first-level:
    - text: Why Go
      url: /learn-more/why-go.html
    - text: Help Doc
      url: http://www.thoughtworks.com/products/docs/go/14.1/help/
      target: blank
- root: Contribute
  url: #
  icon: icon-star-5
  first-level:
    - text: Guide
      url: /contribute/
      second-level:
        - text: Skills needed
          url: /contribute/#skills-needed
        - text: Submit Bug
          url: /contribute/#submit-bug
        - text: Code Contribution Process
          url: /contribute/#code-contribution-process
        - text: Review Process
          url: /contribute/#review-process
        - text: After Code is Accepted
          url: /contribute/#after-commit-is-merged
    - text: CLA
      url: /contribute/cla.html
    - text: Open Issues
      url: https://github.com/GoCD/GoCD/issues?page=1&state=open
      target: blank
    - text: Contributors
      url: https://github.com/GoCD/GoCD/graphs/contributors
      target: blank
- root: Community
  url: #
  icon: icon-group
  first-level:
    - text: Events
      url: /community/events.html
    - text: Resources
      url: /community/resources.html
- root: Download
  url: /download/
  icon: icon-download
