name: GoCD
markdown: redcarpet
permalink: /documentation/:title.html
pygments: false
navigation:
- text: Go Features
  url: /features.html
  layout: default
- text: Download
  url: /download/
  layout: default
- text: Community
  url: /community/
  layout: default
- text: Documentation
  url: /documentation/
  layout: default
- text: Contribute
  url: /contribute/
  layout: default
