name: GoCD
markdown: redcarpet
permalink: /documentation/:title.html
pygments: true
navigation:
# - text: About
#   url: /about/
#   layout: default
# - text: Getting Started
#   url: /getting-started/
#   layout: default
# - text: Why CD with Go?
#   url: /why-go/
#   layout: default
- text: Download
  url: /download/
  layout: default
- text: Community
  url: /community/
  layout: default
- text: Documentation
  url: http://www.thoughtworks.com/products/docs/go/13.4/help/
  layout: default
