name: GoCD
markdown: redcarpet
pygments: false
navigation:
- text: Features
  url: /features.html
  layout: default
- text: Download
  url: /download/
  layout: default
- text: Resources
  url: /community/
  layout: default
- text: Contribute
  url: /contribute/
  layout: default
  text: Issue Tracker
  url: https://github.com/GoCD/GoCD/issues?state=open
- text: Blog
  layout: default
  url: /blog.html
