name: GoCD
markdown: redcarpet
permalink: /documentation/:title.html
pygments: false
navigation:
- text: Why OSS?
  url: /why-oss/
  layout: default
- text: Download
  url: /download/
  layout: default
- text: Community
  url: /community/
  layout: default
- text: Documentation
  url: /documentation/
  layout: default
- text: About Us
  url: /about/
  layout: default