name: GoCD
markdown: redcarpet
permalink: /documentation/:title.html
pygments: false
navigation:
- text: Download
  url: /download/
  layout: default
- text: Community
  url: /community/
  layout: default
- text: Documentation
  url: http://www.thoughtworks.com/products/docs/go/13.4/help/
  layout: default
