name: GoCD
markdown: redcarpet
pygments: false
navigation:
- text: Features
  url: /features/
  layout: default
- text: Download
  url: /download/
  layout: default
- text: Resources
  url: /community/
  layout: default
- text: Contribute
  url: /contribute/
  layout: default
- text: Submit Issue
  url: /contribute/submit-issues.html
- text: Blog
  layout: default
  url: /blog.html
